### ISSUE TITLE
Feature Request: Adding support for ESP32-H2

### ISSUE THREAD

**Issue by matu6968** [tostmann/esp-coordinator#5]
Just like issue #3, i would like to see support for the ESP32-H2 as that seems more similar to the application specific Texas Instruments modules (no Wi-Fi, only 802.15.4/BLE radio) as while the README mentions support for it, no prebuilt binaries exist (only for the ESP32-C6/-C5), that way i don't have to leave unused portions unutulised when using it over native USB since i don't plan on using it as a Zigbee -> Wi-Fi adapter for Z2M.

**Comment by tostmann** [comment]
Thanks — and you're right: the README lists H2 but there's no prebuilt binary for it yet (only C6/C5). We'll get that sorted.

Feasibility looks good. The ZBOSS stack already ships a prebuilt H2 library, and H2 has the same USB-Serial/JTAG controller as the C6, so the native-USB NCP path you want carries straight over — and the multi-target build from v1.4.0 (C6 + C5) makes H2 a natural third target.

The one thing I won't do is publish a binary that has never booted on real H2 silicon. The C5 port had a hardware-only pin gotcha that only surfaced on an actual board, and I'd rather catch that here than have you hit it. So I'm getting an H2 board to validate on before anything goes on the web flasher.

One thing that would help in the meantime: which H2 board do you have, and how much flash does it carry? The current partition layout needs 4 MB. I'll update this issue once there's a build to test.

**Comment by matu6968** [comment]
> Thanks — and you're right: the README lists H2 but there's no prebuilt binary for it yet (only C6/C5). We'll get that sorted.
> 
> Feasibility looks good. The ZBOSS stack already ships a prebuilt H2 library, and H2 has the same USB-Serial/JTAG controller as the C6, so the native-USB NCP path you want carries straight over — and the multi-target build from v1.4.0 (C6 + C5) makes H2 a natural third target.
> 
> The one thing I won't do is publish a binary that has never booted on real H2 silicon. The C5 port had a hardware-only pin gotcha that only surfaced on an actual board, and I'd rather catch that here than have you hit it. So I'm getting an H2 board to validate on before anything goes on the web flasher.
> 
> One thing that would help in the meantime: which H2 board do you have, and how much flash does it carry? The current partition layout needs 4 MB. I'll update this issue once there's a build to test.
> 

I have a ESP32-H2 Supermini board bought from AliExpress seller TENSTAR ROBOT and mine has 4 MB of flash

**Comment by tostmann** [comment]
Perfect, 4 MB is exactly what the current layout needs (`ota_0` is 1900K), so the H2 Supermini fits without touching `partitions.csv`.

Board noted. I'll post a `factory.bin` here to flash once I've validated the build on real H2 silicon — no ETA, but the multi-target plumbing from v1.4.0 means it's mostly bring-up + that one HW check rather than new code.

**Comment by matu6968** [comment]
> Board noted. I'll post a `factory.bin` here to flash once I've validated the build on real H2 silicon — no ETA, but the multi-target plumbing from v1.4.0 means it's mostly bring-up + that one HW check rather than new code.

Compiling it myself resulted in mostly being working after tweaking `CMakeLists.txt` to add a `esp32h2` target:
```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -11,8 +11,8 @@ project(esp-coordinator)
 # `idf.py set-target esp32c6|esp32c5` would silently fall back to the IDF
 # default chip. Turn that into a loud, immediate failure instead of a
 # wrong-chip image.
-if(NOT IDF_TARGET STREQUAL "esp32c6" AND NOT IDF_TARGET STREQUAL "esp32c5")
+if(NOT IDF_TARGET STREQUAL "esp32c6" AND NOT IDF_TARGET STREQUAL "esp32c5" AND NOT IDF_TARGET STREQUAL "esp32h2")
     message(FATAL_ERROR
         "Unsupported IDF_TARGET '${IDF_TARGET}'. "
-        "Run 'idf.py set-target esp32c6' (primary) or 'idf.py set-target esp32c5' first.")
+        "Run 'idf.py set-target esp32c6' (primary), 'idf.py set-target esp32c5' or 'idf.py set-target esp32h2' first.")
 endif()
```
however i ran into some compile errors which where fixed after enabling `'Compiler options' -> 'Disable errors for default warnings'`:
```
In file included from /zram/esp-coordinator/main/commands_impl.h:7,
                 from /zram/esp-coordinator/main/zb_ncp.cpp:21:
/zram/esp-coordinator/main/commands_helpers.h: In instantiation of 'static size_t zb_ncp::general_status_res<CmdId, Res>::process_result(uint8_t*, size_t) [with command_id_t CmdId = GET_SHORT_ADDRESS; Res = short unsigned int; size_t = unsigned int; uint8_t = unsigned char]':
/zram/esp-coordinator/main/commands_helpers.h:169:51:   required from 'static size_t zb_ncp::general_status_res<CmdId, Res>::process_immediate(const void*, size_t, uint8_t*, size_t) [with command_id_t CmdId = GET_SHORT_ADDRESS; Res = short unsigned int; size_t = unsigned int; uint8_t = unsigned char]'
  169 |                 return zb_ncp::cmd_handle<CmdId>::process_result(outdata,outdata_size);
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
/zram/esp-coordinator/main/commands_helpers.h:34:69:   required from 'static void zb_ncp::immediate_cmd_process<CmdId>::process(const zb_ncp::cmd_t&, const void*, size_t) [with command_id_t CmdId = GET_SHORT_ADDRESS; size_t = unsigned int]'
   34 |         auto outlen = sizeof(zb_ncp::cmd_t) + Cmd::process_immediate(buffer,len,&outdata[sizeof(zb_ncp::cmd_t)],sizeof(outdata)-sizeof(zb_ncp::cmd_t));
      |                                               ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/zram/esp-coordinator/main/commands_list.h:29:1:   required from here
  359 |             cmd_handle<Name>::process(cmd, buf, len); \
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
/zram/esp-coordinator/main/commands_helpers.h:165:87: error: taking address of packed member of 'zb_ncp::general_status_res<GET_SHORT_ADDRESS, short unsigned int>::FullRes' may result in an unaligned pointer value [-Werror=address-of-packed-member]
  165 |                 zb_ncp::cmd_handle<CmdId>::process_status_res(full_res->status.status,&full_res->res);
      |                                                                                       ^~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

I am yet to test this via Zigbee2MQTT to see if it works as expected as in only checked if it will compile

**Comment by tostmann** [comment]
Good catch on the compile — and you don't need the "disable errors for default warnings" toggle. That error has a single real cause, now fixed in-tree:

- `GET_SHORT_ADDRESS` was taking `&full_res->res` as a plain `uint16_t*` into a `__attribute__((packed))` wire buffer, which trips `-Werror=address-of-packed-member` on stricter toolchains (IDF 6.x / newer GCC). It now uses the byte-aligned `unaligned_uint16_t*` typedef, exactly like `GET_PAN_ID` already did. It was the only offender across the whole command surface.
- The `CMakeLists.txt` multi-target guard now accepts `esp32h2` alongside `esp32c6`/`esp32c5` (same diff you found).

So a clean checkout builds for H2 with no warning-disabling needed. I verified the full H2 build on IDF 5.5.3 (app ~604 KB, fits the 1900K `ota_0`).

A test build for your H2 Supermini (4 MB) is here:

https://install.busware.de/zboss/esp-coordinator-esp32h2-factory-testing.bin

Flash it at offset 0:

```
esptool --chip esp32h2 write_flash 0x0 esp-coordinator-esp32h2-factory-testing.bin
```

This is **strictly a test build** — it has never booted on real H2 silicon (I don't have an H2 board in hand yet), so it's not on the web flasher and not a release. Please flash it and let me know: does it boot, and does Z2M (`adapter: zboss`) bring it up over native USB? If it works on your hardware, that's the validation gate I need before any official H2 binary.

**Comment by matu6968** [comment]
> A test build for your H2 Supermini (4 MB) is here:
> 
> https://install.busware.de/zboss/esp-coordinator-esp32h2-factory-testing.bin
> 
> Flash it at offset 0:
> 
> ```
> esptool --chip esp32h2 write_flash 0x0 esp-coordinator-esp32h2-factory-testing.bin
> ```
> 
> This is **strictly a test build** — it has never booted on real H2 silicon (I don't have an H2 board in hand yet), so it's not on the web flasher and not a release. Please flash it and let me know: does it boot, and does Z2M (`adapter: zboss`) bring it up over native USB? If it works on your hardware, that's the validation gate I need before any official H2 binary.

Both binaries work on a ESP32-H2 revision v0.1 silicon (xxd output):

**Test build** (from esp-coordinator-esp32h2-factory-testing.bin) :
```
00000000: 4553 502d 524f 4d3a 6573 7033 3268 322d  ESP-ROM:esp32h2-
00000010: 3230 3232 3131 3031 0a42 7569 6c64 3a4e  20221101.Build:N
00000020: 6f76 2020 3120 3230 3232 0a72 7374 3a30  ov  1 2022.rst:0
00000030: 7831 3520 2855 5342 5f55 4152 545f 4850  x15 (USB_UART_HP
00000040: 5359 5329 2c62 6f6f 743a 3078 3820 2853  SYS),boot:0x8 (S
00000050: 5049 5f46 4153 545f 464c 4153 485f 424f  PI_FAST_FLASH_BO
00000060: 4f54 290a 5361 7665 6420 5043 3a30 7834  OT).Saved PC:0x4
00000070: 3038 3033 3961 360a 5350 4957 503a 3078  08039a6.SPIWP:0x
00000080: 6565 0a6d 6f64 653a 4449 4f2c 2063 6c6f  ee.mode:DIO, clo
00000090: 636b 2064 6976 3a31 0a6c 6f61 643a 3078  ck div:1.load:0x
000000a0: 3430 3834 3630 6630 2c6c 656e 3a30 7835  408460f0,len:0x5
000000b0: 3663 0a6c 6f61 643a 3078 3430 3833 6332  6c.load:0x4083c2
000000c0: 6430 2c6c 656e 3a30 7863 6430 0a6c 6f61  d0,len:0xcd0.loa
000000d0: 643a 3078 3430 3833 6566 6430 2c6c 656e  d:0x4083efd0,len
000000e0: 3a30 7832 3562 340a 656e 7472 7920 3078  :0x25b4.entry 0x
000000f0: 3430 3833 6332 6430 0ade ad05 0006 018f  4083c2d0........
00000100: dead 0e00 06c0 5d50 d400 0102 00ff 0000  ......]P........
```
**Local build**:

```
00000000: 4553 502d 524f 4d3a 6573 7033 3268 322d  ESP-ROM:esp32h2-
00000010: 3230 3232 3131 3031 0a42 7569 6c64 3a4e  20221101.Build:N
00000020: 6f76 2020 3120 3230 3232 0a72 7374 3a30  ov  1 2022.rst:0
00000030: 7831 3520 2855 5342 5f55 4152 545f 4850  x15 (USB_UART_HP
00000040: 5359 5329 2c62 6f6f 743a 3078 6220 2853  SYS),boot:0xb (S
00000050: 5049 5f46 4153 545f 464c 4153 485f 424f  PI_FAST_FLASH_BO
00000060: 4f54 290a 5361 7665 6420 5043 3a30 7834  OT).Saved PC:0x4
00000070: 3030 3062 3965 360a 5350 4957 503a 3078  000b9e6.SPIWP:0x
00000080: 6565 0a6d 6f64 653a 4449 4f2c 2063 6c6f  ee.mode:DIO, clo
00000090: 636b 2064 6976 3a31 0a6c 6f61 643a 3078  ck div:1.load:0x
000000a0: 3430 3834 3630 6630 2c6c 656e 3a30 7835  408460f0,len:0x5
000000b0: 3638 0a6c 6f61 643a 3078 3430 3833 6332  68.load:0x4083c2
000000c0: 6430 2c6c 656e 3a30 7864 3038 0a6c 6f61  d0,len:0xd08.loa
000000d0: 643a 3078 3430 3833 6566 6430 2c6c 656e  d:0x4083efd0,len
000000e0: 3a30 7832 3563 380a 656e 7472 7920 3078  :0x25c8.entry 0x
000000f0: 3430 3833 6332 6430 0ade ad05 0006 01ef  4083c2d0........
00000100: bfbd dead 0e00 06ef bfbd 5d50 efbf bd00  ..........]P....
00000110: 0102 000a
```
I have not yet connected it to Zigbee2MQTT and only performed a power on with this firmware

**Comment by tostmann** [comment]
That dump is exactly the validation I was after: your self-compiled build **boots on real H2 silicon (rev v0.1)** and the `DE AD …` bytes at the tail of your log are the NCP boot-ready frames — so the firmware is up and the ZBOSS NCP serial protocol is alive on H2. The fixes are now in-tree (the `unaligned_uint16_t*` change for `GET_SHORT_ADDRESS` and the `esp32h2` target guard), so a clean checkout builds without the "disable errors for default warnings" toggle. The one step left is to point Z2M (`adapter: zboss`) at it over native USB and confirm it comes up as a coordinator — your own build is the right thing to take to that test.

On the broken `factory.bin`: that's a corrupted download, not a bad image. `invalid header: 0x0a0a0a0a` means the ROM read repeated newline bytes at flash offset 0x0 — the signature of a text/HTML response saved as the file rather than the binary. The published file is intact; a fresh download from the URL is byte-identical to what I built and starts with the valid `0xE9` ESP image magic, not `0x0a`. If you want to check your copy:

- size: exactly **735504 bytes**
- md5: **75eb108925fabee6c2b7b02062ce97fa**

If it doesn't match, re-fetch with something that won't text-mangle it (`wget -O esp-coordinator-esp32h2-factory-testing.bin <url>` / `curl -o … <url>`) and flash with `esptool --chip esp32h2 write_flash 0x0 …`. But since your own build already boots, that test bin is just a convenience — no need to chase it if your build works for the Z2M step.

**Comment by matu6968** [comment]
Okay, last time i downloaded the binary with wget i accidentally downloaded the issue page (https://github.com/tostmann/esp-coordinator/issues/5) and not the binary which was what i thought it downloaded, redownloading the binary with curl at the right address gave the same NCP output

**Comment by matu6968** [comment]
testing it with Zigbee2MQTT works:
```
[17:05:51] INFO: Preparing to start...
[17:05:51] INFO: Socat not enabled
[17:05:52] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
Onboarding page is available at http://0.0.0.0:8099/
[2026-06-18 17:06:38] info: 	z2m: Logging to console, file (filename: log.log)
[2026-06-18 17:06:38] info: 	z2m: External JS (converters/extensions) is disabled
[2026-06-18 17:06:38] info: 	z2m: Starting Zigbee2MQTT version 2.12.0 (commit #unknown)
[2026-06-18 17:06:38] info: 	z2m: Starting zigbee-herdsman (10.4.0)
[2026-06-18 17:06:38] info: 	zh:zboss: ZBOSS Adapter starting
[2026-06-18 17:06:38] info: 	zh:zboss:driv: Driver connecting
[2026-06-18 17:06:38] info: 	zh:zboss:uart: NCP reset
[2026-06-18 17:06:38] info: 	zh:zboss:uart: Serial port opened
[2026-06-18 17:06:38] info: 	zh:zboss:uart: UART starting
[2026-06-18 17:06:38] info: 	zh:zboss:driv: Driver connected
[2026-06-18 17:06:38] info: 	zh:zboss:driv: Driver startup
[2026-06-18 17:06:38] info: 	zh:zboss:driv: Form network
[2026-06-18 17:06:39] info: 	z2m: zigbee-herdsman started (reset)
[2026-06-18 17:06:39] info: 	z2m: Coordinator firmware version: '{"meta":{"coordinator":0,"protocol":"0.0.0.2","revision":"1.4.0.59","stack":"3.15.0.0"},"type":"zboss"}'
[2026-06-18 17:06:39] info: 	z2m: Currently 0 devices are joined.
[2026-06-18 17:06:39] info: 	z2m: Connecting to MQTT server at mqtt://core-mosquitto:1883
[2026-06-18 17:06:39] info: 	z2m: Connected to MQTT server
[2026-06-18 17:06:39] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"online"}'
[2026-06-18 17:06:39] info: 	z2m: Started frontend on port 8099
[2026-06-18 17:06:40] info: 	z2m: Zigbee2MQTT started!
[2026-06-18 17:06:45] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/binary_sensor/1221051039810110150109113116116_0x47e962feffdb5110/connection_state/config', payload '{"default_entity_id":"binary_sensor.zigbee2mqtt_bridge_connection_state","device":{"hw_version":"zboss 1.4.0.59","identifiers":["zigbee2mqtt_bridge_0x47e962feffdb5110"],"manufacturer":"Zigbee2MQTT","model":"Bridge","name":"Zigbee2MQTT Bridge","sw_version":"2.12.0"},"device_class":"connectivity","entity_category":"diagnostic","name":"Connection state","object_id":"zigbee2mqtt_bridge_connection_state","origin":{"name":"Zigbee2MQTT","sw":"2.12.0","url":"https://www.zigbee2mqtt.io"},"payload_off":"offline","payload_on":"online","state_topic":"zigbee2mqtt/bridge/state","unique_id":"bridge_0x47e962feffdb5110_connection_state_zigbee2mqtt","value_template":"{{ value_json.state }}"}'
[2026-06-18 17:06:45] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/binary_sensor/1221051039810110150109113116116_0x47e962feffdb5110/restart_required/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"availability_mode":"all","default_entity_id":"binary_sensor.zigbee2mqtt_bridge_restart_required","device":{"hw_version":"zboss 1.4.0.59","identifiers":["zigbee2mqtt_bridge_0x47e962feffdb5110"],"manufacturer":"Zigbee2MQTT","model":"Bridge","name":"Zigbee2MQTT Bridge","sw_version":"2.12.0"},"device_class":"problem","enabled_by_default":false,"entity_category":"diagnostic","name":"Restart required","object_id":"zigbee2mqtt_bridge_restart_required","origin":{"name":"Zigbee2MQTT","sw":"2.12.0","url":"https://www.zigbee2mqtt.io"},"payload_off":false,"payload_on":true,"state_topic":"zigbee2mqtt/bridge/info","unique_id":"bridge_0x47e962feffdb5110_restart_required_zigbee2mqtt","value_template":"{{ value_json.restart_required }}"}'
[2026-06-18 17:06:45] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/button/1221051039810110150109113116116_0x47e962feffdb5110/restart/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"availability_mode":"all","command_topic":"zigbee2mqtt/bridge/request/restart","default_entity_id":"button.zigbee2mqtt_bridge_restart","device":{"hw_version":"zboss 1.4.0.59","identifiers":["zigbee2mqtt_bridge_0x47e962feffdb5110"],"manufacturer":"Zigbee2MQTT","model":"Bridge","name":"Zigbee2MQTT Bridge","sw_version":"2.12.0"},"device_class":"restart","name":"Restart","object_id":"zigbee2mqtt_bridge_restart","origin":{"name":"Zigbee2MQTT","sw":"2.12.0","url":"https://www.zigbee2mqtt.io"},"payload_press":"","unique_id":"bridge_0x47e962feffdb5110_restart_zigbee2mqtt"}'
[2026-06-18 17:06:45] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/select/1221051039810110150109113116116_0x47e962feffdb5110/log_level/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"availability_mode":"all","command_template":"{\"options\": {\"advanced\": {\"log_level\": \"{{ value }}\" } } }","command_topic":"zigbee2mqtt/bridge/request/options","default_entity_id":"select.zigbee2mqtt_bridge_log_level","device":{"hw_version":"zboss 1.4.0.59","identifiers":["zigbee2mqtt_bridge_0x47e962feffdb5110"],"manufacturer":"Zigbee2MQTT","model":"Bridge","name":"Zigbee2MQTT Bridge","sw_version":"2.12.0"},"entity_category":"config","name":"Log level","object_id":"zigbee2mqtt_bridge_log_level","options":["error","warning","info","debug"],"origin":{"name":"Zigbee2MQTT","sw":"2.12.0","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt/bridge/info","unique_id":"bridge_0x47e962feffdb5110_log_level_zigbee2mqtt","value_template":"{{ value_json.log_level | lower }}"}'
[2026-06-18 17:06:45] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/1221051039810110150109113116116_0x47e962feffdb5110/version/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"availability_mode":"all","default_entity_id":"sensor.zigbee2mqtt_bridge_version","device":{"hw_version":"zboss 1.4.0.59","identifiers":["zigbee2mqtt_bridge_0x47e962feffdb5110"],"manufacturer":"Zigbee2MQTT","model":"Bridge","name":"Zigbee2MQTT Bridge","sw_version":"2.12.0"},"entity_category":"diagnostic","icon":"mdi:zigbee","name":"Version","object_id":"zigbee2mqtt_bridge_version","origin":{"name":"Zigbee2MQTT","sw":"2.12.0","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt/bridge/info","unique_id":"bridge_0x47e962feffdb5110_version_zigbee2mqtt","value_template":"{{ value_json.version }}"}'
[2026-06-18 17:06:45] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/1221051039810110150109113116116_0x47e962feffdb5110/coordinator_version/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"availability_mode":"all","default_entity_id":"sensor.zigbee2mqtt_bridge_coordinator_version","device":{"hw_version":"zboss 1.4.0.59","identifiers":["zigbee2mqtt_bridge_0x47e962feffdb5110"],"manufacturer":"Zigbee2MQTT","model":"Bridge","name":"Zigbee2MQTT Bridge","sw_version":"2.12.0"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:chip","name":"Coordinator version","object_id":"zigbee2mqtt_bridge_coordinator_version","origin":{"name":"Zigbee2MQTT","sw":"2.12.0","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt/bridge/info","unique_id":"bridge_0x47e962feffdb5110_coordinator_version_zigbee2mqtt","value_template":"{{ value_json.coordinator.meta.revision }}"}'
[2026-06-18 17:06:45] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/1221051039810110150109113116116_0x47e962feffdb5110/network_map/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"availability_mode":"all","default_entity_id":"sensor.zigbee2mqtt_bridge_network_map","device":{"hw_version":"zboss 1.4.0.59","identifiers":["zigbee2mqtt_bridge_0x47e962feffdb5110"],"manufacturer":"Zigbee2MQTT","model":"Bridge","name":"Zigbee2MQTT Bridge","sw_version":"2.12.0"},"enabled_by_default":false,"entity_category":"diagnostic","json_attributes_template":"{{ value_json.data.value | tojson }}","json_attributes_topic":"zigbee2mqtt/bridge/response/networkmap","name":"Network map","object_id":"zigbee2mqtt_bridge_network_map","origin":{"name":"Zigbee2MQTT","sw":"2.12.0","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt/bridge/response/networkmap","unique_id":"bridge_0x47e962feffdb5110_network_map_zigbee2mqtt","value_template":"{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"}'
[2026-06-18 17:06:45] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/switch/1221051039810110150109113116116_0x47e962feffdb5110/permit_join/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"availability_mode":"all","command_topic":"zigbee2mqtt/bridge/request/permit_join","default_entity_id":"switch.zigbee2mqtt_bridge_permit_join","device":{"hw_version":"zboss 1.4.0.59","identifiers":["zigbee2mqtt_bridge_0x47e962feffdb5110"],"manufacturer":"Zigbee2MQTT","model":"Bridge","name":"Zigbee2MQTT Bridge","sw_version":"2.12.0"},"icon":"mdi:human-greeting-proximity","name":"Permit join","object_id":"zigbee2mqtt_bridge_permit_join","origin":{"name":"Zigbee2MQTT","sw":"2.12.0","url":"https://www.zigbee2mqtt.io"},"payload_off":"{\"time\": 0}","payload_on":"{\"time\": 254}","state_off":"false","state_on":"true","state_topic":"zigbee2mqtt/bridge/info","unique_id":"bridge_0x47e962feffdb5110_permit_join_zigbee2mqtt","value_template":"{{ value_json.permit_join | lower }}"}'
```

**Comment by tostmann** [comment]
That's the gate cleared — thanks for taking it all the way to Z2M.

Your log shows the firmware booting on real H2 silicon (rev v0.1) and Zigbee2MQTT (`adapter: zboss`) bringing it up over native USB: it forms a network, reports `revision 1.4.0.59`, and starts cleanly. That's exactly the end-to-end validation I wanted before treating H2 as a real target.

The fixes are in-tree (the `unaligned_uint16_t*` change for `GET_SHORT_ADDRESS` and the `esp32h2` target guard), so a clean checkout builds for H2 with no warning-disabling — your self-built image is the right thing to keep running for now.

One deliberate hold: I'm not putting an H2 binary on the web flasher or cutting an official release just yet. Your H2 Supermini (rev v0.1) is a solid datapoint, but it's a single board on one silicon rev, and the C5 port taught me that board-level pin gotchas only surface on real hardware. I've got an H2 board on the way and want to boot it myself before publishing — same caution I applied to C5. Once that's done, H2 goes on the web flasher as the third target and into a tagged release; I'll update this issue when it ships.

If anything misbehaves on yours in the meantime — especially around USB reset / re-enumeration or pairing — that's exactly the kind of thing I'd want to hear before it's official.

**Comment by josteinh** [comment]
Thank you!

I have tested image on a WeAct ESP32H2-N4 board.
It seems to works great with ZHA. (I have not tested with Z2M)

**Comment by tostmann** [comment]
Thanks for the second datapoint — and on a different board than the first report. Your WeAct ESP32H2-N4 running cleanly with ZHA is useful precisely because it covers ground the earlier report didn't: a different board layout, and the zigpy-zboss/ZHA side rather than Z2M. Two independent H2 boards now, both stacks — a solid signal that the multi-target build carries over to H2 without surprises.

It doesn't change the release gate, and I want to be straight about why: I still won't put an H2 binary on the web flasher or cut a tagged release until I've booted it on my own H2 silicon. The C5 port had a board-level pin gotcha that only surfaced on real hardware, and a couple of good third-party reports — however welcome — aren't a substitute for that. I have an H2 board on the way; once it boots here, H2 goes on the web flasher as the third official target and into a tagged release, and I'll update this issue when it ships.

Keep running the test build in the meantime — if anything misbehaves around USB reset / re-enumeration or pairing, that's exactly the kind of thing worth hearing before it's official.

**Comment by tostmann** [comment]
@matu6968 @josteinh — the official **ESP32-H2** build is now live. 🎉

Following your reports (Z2M on the H2 Supermini, and ZHA on the WeAct ESP32H2-N4 — thanks again; two boards and two host stacks were exactly the external coverage this needed), I've now validated it end-to-end on H2 silicon on the bench here as well: boot + NCP over native USB-Serial/JTAG, 802.15.4 network formation, NVRAM resume across a reboot, and on-air pairing of a real Zigbee device (join → authorize → interview).

Shipped as **v1.5.0**:
- Web flasher auto-detects and serves the H2 image alongside C6/C5: https://install.busware.de/zboss/
- Release notes: https://github.com/tostmann/esp-coordinator/releases/tag/v1.5.0

Two notes for H2 boards: the 1900K application partition needs a **4 MB flash** part (e.g. ESP32-H2-MINI-1), and since the H2 has no Wi-Fi the Wi-Fi-coexistence build does not apply — it's a pure USB/UART coordinator.

**Comment by matu6968** [comment]
Had to wipe the ESP32-H2 when upgrading to 1.5.0 otherwaise it would not connect to Zigbee2MQTT but otherwaise it works now so i am closing the issue

**Comment by tostmann** [comment]
Perfect, thanks for confirming on real H2 silicon — that's the first field report on the *published* v1.5.0 build rather than a hand-built image, so it's a nice milestone 🎉

The wipe-on-upgrade makes sense: jumping from a self-built pre-1.5.0 image, a persisted ZBOSS dataset in `nvs`/`zb_storage` that the newer build won't resume is the usual suspect — z2m then never sees a coordinator until a full erase forces a fresh formation, which is why it came up clean. Expected across hand-built builds; if you ever hit it on a plain v1.5.x → v1.5.y bump, that would be a real bug — ping me and I'll dig in. Reopen anytime. Cheers!
